/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Display404: typeof import('./src/components/Display404.vue')['default']
    DownloadReleaseAsset: typeof import('./src/components/DownloadReleaseAsset.vue')['default']
    FeaturePanels: typeof import('./src/components/FeaturePanels.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionMenu: typeof import('./src/components/SectionMenu.vue')['default']
  }
}
