/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/community-services/': RouteRecordInfo<'/community-services/', '/community-services', Record<never, never>, Record<never, never>>,
    '/community-services/adoption-guidance': RouteRecordInfo<'/community-services/adoption-guidance', '/community-services/adoption-guidance', Record<never, never>, Record<never, never>>,
    '/community-services/redirect-hosting': RouteRecordInfo<'/community-services/redirect-hosting', '/community-services/redirect-hosting', Record<never, never>, Record<never, never>>,
    '/community-services/support-venues': RouteRecordInfo<'/community-services/support-venues', '/community-services/support-venues', Record<never, never>, Record<never, never>>,
    '/download': RouteRecordInfo<'/download', '/download', Record<never, never>, Record<never, never>>,
    '/features/': RouteRecordInfo<'/features/', '/features', Record<never, never>, Record<never, never>>,
    '/features/archivist': RouteRecordInfo<'/features/archivist', '/features/archivist', Record<never, never>, Record<never, never>>,
    '/features/catalog': RouteRecordInfo<'/features/catalog', '/features/catalog', Record<never, never>, Record<never, never>>,
    '/features/manifest-editor': RouteRecordInfo<'/features/manifest-editor', '/features/manifest-editor', Record<never, never>, Record<never, never>>,
    '/features/mod-health': RouteRecordInfo<'/features/mod-health', '/features/mod-health', Record<never, never>, Record<never, never>>,
    '/features/parlay': RouteRecordInfo<'/features/parlay', '/features/parlay', Record<never, never>, Record<never, never>>,
    '/privacy-policy': RouteRecordInfo<'/privacy-policy', '/privacy-policy', Record<never, never>, Record<never, never>>,
    '/redirect': RouteRecordInfo<'/redirect', '/redirect', Record<never, never>, Record<never, never>>,
    '/terms-of-use': RouteRecordInfo<'/terms-of-use', '/terms-of-use', Record<never, never>, Record<never, never>>,
    '/who-are-we': RouteRecordInfo<'/who-are-we', '/who-are-we', Record<never, never>, Record<never, never>>,
  }
}
